using System;
using FiresCore.Logging;
using UnityEngine;

namespace FiresEasyBakeMeshes
{
    // FiresEasyBakeMeshes' console banners, rendered through the shared Banner engine.
    //
    //   PrintBig()  → oven with a mesh cube glowing in the window. Fires at the
    //                 very top of Awake so the load log opens with the bakery.
    //   Print()     → compact oven under heat squiggles over a status frame
    //                 ("OVEN HOT"). Fires once when ZNetScene is ready.
    //
    // Art generated by Tools\gen_fires_banner.ps1 (spec: FiresEasyBakeMeshes).
    internal static class FiresEasyBakeBanner
    {
        private static bool s_compactPrinted;

        public static void PrintBig()
        {
            try
            {
                EmitHeader("Fires Easy Bake Meshes Loading...");
                Banner.Print(ToSegments(s_bigLines));
            }
            catch (Exception ex)
            {
                Debug.LogWarning($"[FiresEasyBakeMeshes] Big banner failed: {ex.Message}");
            }
        }

        public static void Print()
        {
            if (s_compactPrinted) return;
            s_compactPrinted = true;
            try
            {
                EmitHeader("Fires Easy Bake Meshes Loaded.");
                Banner.Print(s_compactLines);
            }
            catch (Exception ex)
            {
                Debug.LogWarning($"[FiresEasyBakeMeshes] Compact banner failed: {ex.Message}");
            }
        }

        // Routes the one-line header through the plugin's BepInEx log source so
        // it prints once, colored by FiresLogColorPatch via the mod source name,
        // without a raw white stdout duplicate.
        private static void EmitHeader(string text)
        {
            if (EasyBakeLog.Source != null) EasyBakeLog.Source.LogInfo(text);
            else Debug.Log($"[FiresEasyBakeMeshes] {text}");
        }

        private static Banner.Segment[][] ToSegments((string text, ConsoleColor color)[] lines)
        {
            var result = new Banner.Segment[lines.Length][];
            for (int i = 0; i < lines.Length; i++)
                result[i] = new[] { new Banner.Segment(lines[i].text, lines[i].color) };
            return result;
        }

        // Compact banner — oven under heat squiggles over a status frame. 31-char
        // frame body (3 lead + ╔ + 26 ═ + ╗); 🧱 is a surrogate pair that renders
        // 2 cells, so the status line's padding assumes an emoji-aware console font.
        private static readonly Banner.Segment[][] s_compactLines =
        {
            new[] { new Banner.Segment("                ) ) )",        ConsoleColor.Yellow) },
            new[] { new Banner.Segment("               ( ( (",         ConsoleColor.DarkYellow) },
            new[] { new Banner.Segment("            ┌───────────┐",    ConsoleColor.DarkGray) },
            new[]
            {
                new Banner.Segment("            │ ",       ConsoleColor.DarkGray),
                new Banner.Segment("▌ ▣ ▣ ▣ ▐",            ConsoleColor.Red),
                new Banner.Segment(" │",                   ConsoleColor.DarkGray),
            },
            new[] { new Banner.Segment("            └───────────┘",    ConsoleColor.DarkGray) },
            new[] { new Banner.Segment("   ╔══════════════════════════╗", ConsoleColor.DarkGray) },
            new[]
            {
                new Banner.Segment("   ║   ",              ConsoleColor.DarkGray),
                new Banner.Segment("[",                    ConsoleColor.Gray),
                new Banner.Segment("██████████████████",   ConsoleColor.Green),
                new Banner.Segment("]",                    ConsoleColor.Gray),
                new Banner.Segment("   ║",                 ConsoleColor.DarkGray),
            },
            new[]
            {
                new Banner.Segment("   ║        ",         ConsoleColor.DarkGray),
                new Banner.Segment("🧱 OVEN HOT",          ConsoleColor.Yellow),
                new Banner.Segment("       ║",             ConsoleColor.DarkGray),
            },
            new[] { new Banner.Segment("   ╚══════════════════════════╝", ConsoleColor.DarkGray) },
            new[] { new Banner.Segment("    FIRES EASY BAKE MESHES",   ConsoleColor.Cyan) },
            new Banner.Segment[0],
            new[] { new Banner.Segment("   Fires Easy Bake Meshes Loaded", ConsoleColor.Magenta) },
        };

        private static readonly (string text, ConsoleColor color)[] s_bigLines =
        {
            ("", ConsoleColor.Gray),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.Red),
            ("%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%++%%%@%%%%%%++%%%%%%%%%%++%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkRed),
            ("%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%==+%%%%%%%%%==+%%@@%%%%%==+%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.Red),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%+=@%%%%%%%%%+=@%%%%%%%%%+=@%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkRed),
            ("%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%@%%%+=%%++%%%%%%+=%%++%%%%%%+=%%++%%%%%%@%%%%%%%%%%%%%%@%%%%%%%@%%%", ConsoleColor.Red),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%+=%@+==*%%%%+=%%+==*%%%%+=%%+==*%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%", ConsoleColor.DarkRed),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%==+%%=+%%%%%==+%%=+%%%%%==+%%=+%%%%%%%%%%%%@%%%%%%%%%@%%%%%%%%", ConsoleColor.Red),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%++%%+=%%%%%%++@%+=%%%%%%++%%+=%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkRed),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%==%%%%%%%%%%==%%%%%%%%%%==%%@%%%%%%%%%%%%%%%%%%@%%%%%%%%%", ConsoleColor.Red),
            ("%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%++=+%%%%%%%%++=+%%%%%%%%++=+%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.Yellow),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%-:::::::::::::::::::::::::::::::::::::::::::*%%%%%%%%%%%%%%@%%%%%%%%%%%%", ConsoleColor.DarkYellow),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%-:::::::::::::::::::::::::::::::::::::::::::*%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.Yellow),
            ("%%%%%%%%%%@@%%%%%%%%%%%%%%%%-:::::::::::::::::::::::::::::::::::::::::::*%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkYellow),
            ("%%%%%%%%%%%%%%%%%%%@%%%%%%%%-::+*************************************-::*%%%%%%%%%@%%%%%%%%%%%%%%%%%", ConsoleColor.Yellow),
            ("%%%%%%%%%%%%%%%%%%%%%%@%%%%%-::*%%@%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%-::*%%%%%%%@%%%%%%%%%%%%%%%@%%%", ConsoleColor.DarkYellow),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%-::*%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%-::*%%%%%%%%%%%%%%@%%%%%%%%%%%%", ConsoleColor.Yellow),
            ("%%%%%%%@%%%%%%%%%%@%%%%%%%%%-::*@%%%@%%%%%%--::::::::::--%%%%%%%%%%%%-::*%%%%%%%%@%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkYellow),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%@-::*%%%%%%%%#-:..............:--%%%%%%%%%-::*%%%%%%%%%%%%%@%%%%%%%@%%@%%", ConsoleColor.Yellow),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%-::*%%%%%%%-:...::-------::.....-*%%%%%%%-::*%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkYellow),
            ("%%%%%%%%%%%%%%%%%%%%%@%%%%%%-::*%@%%%*:...:-%%-:--------:....:-%%%%%%-::*%%%%%%%%%%%%%%%%%%%%%%%@%%%", ConsoleColor.Yellow),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%-::*%%%%%:..:-%%-::--------::-::..:-%%%%%-::*%%@%%%%%%%%%%%@%%%%%%%%%%%%", ConsoleColor.DarkYellow),
            ("%%@%%%%%%%%%%%%%%@%%%%%%%%%%-::*%%%%-..:-%@%-:--------::%-:@:..:%%%%%-::*%%@%%%%%%%%%%%@%%%%%%%%@%@%", ConsoleColor.Yellow),
            ("%%%%%%%%%%%%%%%@%%%%%%%%%%%%-::*%%%%:..-%%%%-:%%%%%%%%-:%-:%-...@%%%%-::*%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkYellow),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%-::*%%%%:..-%%%%-:%%%%%%%%-:%-:%%:..*%%%%-::*%%%%%%%%%%%%%%%%%@%%%%%%%%%", ConsoleColor.Yellow),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%-::*%%%%:..-%%%%-:%%%%%%%%-:%-:%-...#%%%%-::*%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkYellow),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%-::*%%%%-..:-%%%-:%%%%%%%%-:-:-%:..:%%%%%-::*%%%%%%%%%%%%%@%%%%%%%%%%%%%", ConsoleColor.Yellow),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%-::*%%%%%:..:-%%-:---------.:+=:..:-%%%%%-::*%%%%%%%%%%%%%%%%%%%%%%%%%@%", ConsoleColor.DarkYellow),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%@-::*%%%%%-:...:-------------=-:..:-%%%%%%-::*%%@%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.Yellow),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%-::*%%%%%%@-....:---%%%%---:....:-%%%%%%%-::*%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkYellow),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%-::*%@%%%%%%--:...............:-%%%%%%%%%-::*%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.Yellow),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%-::*%%%%%%%%%%%--::......:::-*%%%%%%%%%%%-::*%%%%%%%%%%%%@%%%%%%%%%%%%%%", ConsoleColor.DarkYellow),
            ("@%%%%%%%%%%@%%%%%%%%%%%%%%%%-::*%%%%%%%%%%%%%%%%%**#%%%%%%%%%%%@%%%%@-::*%%%%%%%%%%%%%%%%@%%%%%%%@%%", ConsoleColor.Yellow),
            ("%%%%@%%%%%%%%%%%%%%%%%%%%%%%-::*%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%-::*%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkYellow),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%-::*%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%-::*%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.Yellow),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%-::*%%%%%%%%%%%%%%@%@%%@%%%%%%%%%%%%%%%%%-::*%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkYellow),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%-:::::::::::::::::::::::::::::::::::::::::::*%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.Yellow),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%@%-:::::::::::::::::::::::::::::::::::::::::::*%%%@%%%%%%%%%%%%%%%%%@%%%%%", ConsoleColor.DarkYellow),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%-:::::::::::::::::::::::::::::::::::::::::::*%%%%%%@%%@%%%%%%%%%%%%%%%%%", ConsoleColor.Yellow),
            ("%%%%%%%%%%%%%%%%%%@%%%@%%%%%**-::::+*****************************-::::+*#%%%%%%%%%%@%%%%%%%%%%%%%%%%", ConsoleColor.DarkYellow),
            ("@%%@%%%%%%%%%%%%%%%%%%%%%%%%%%-::::*%%%%%%%@@@%%%%%%%%%%%%%%%%%%%-::::*%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkGray),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%*****#%%%%%%%%%@%%%%%%%%%%%%%%%%%%%*****#%%%%%%%%%%%@%%%%%%%%%%%%%%%%%", ConsoleColor.DarkGray),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%", ConsoleColor.DarkGray),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%", ConsoleColor.DarkGray),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkGray),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkGray),
            ("%%%%%%%%%%%%%%%%%%@%%%%%%@%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkGray),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.Yellow),
            ("%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.White),
            ("%%%%%%%@-:::::::%%:::::::%%#::....:-%-:::-%::::#%%%-::::::::-%%%::::::-%%-::::%::::--:::::::%%%%%%%%", ConsoleColor.Yellow),
            ("%%%%%%%%-......:%%......:%%:...::...-#...:-...:%%%%-....:....%%+......:%%:...:-...:%-......:%%%%%%%%", ConsoleColor.White),
            ("%%%%%%%%-...:%%%%-...:...=%:...:-:::-%-...:...%%@%%-....%:...%%-.......%%:...:....-%-...:%%%%%%%%%%%", ConsoleColor.Yellow),
            ("%%%%%%%%-....::-%:...:...-%-.....:-@%%%:.....-%%%%@-....:...:%%:...-...-%:.......-%%-....::-%%%%%%%%", ConsoleColor.White),
            ("%%%%%%%%-......-%:...@...:%%-::.....-%%-....:%%%%%%-....:...:-%....-...:%:.......:%%-......-%%%%%%%%", ConsoleColor.Yellow),
            ("%%%%%%%%-...:%%%@....:....%-:::-:...:%%%:...-%@%@%%-....%:...--....:....%:........-%-...:%%%%%%%%%%%", ConsoleColor.White),
            ("%%%%%%%%-....::--....:....-:...:-...:%%%:...+%%%%%%-....-....-:....:....-:...::...:%-....::-%%%%%%%%", ConsoleColor.Yellow),
            ("%%%%%%%%-.......:...:%:...:-:.......-%%@:...+%%%%%%-.........-:...:%:...::...:=....--......:%%%%%%%%", ConsoleColor.White),
            ("%%%%%%@%-------------%-----%%------%%%%%----+%%%%%%---------%%-----%----------%-------------%%%%%%%@", ConsoleColor.Yellow),
            ("%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%", ConsoleColor.White),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%@%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.Yellow),
            ("@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%@%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.White),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%@%%%%%%%%", ConsoleColor.Yellow),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.White),
            ("%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.Yellow),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%@%%%%%@@%@%%%%%%%%%%%%%@%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkGray),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkGray),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkGray),
            ("@%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkGray),
            ("@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%", ConsoleColor.DarkGray),
            ("", ConsoleColor.Gray),
        };
    }
}
